Repository IUS-CS/c346-fa23-project-team-rocket, pull requests merged in 2023-10, with the labels that each got.

#48 Doc/designpattern
  doc/designpatterns.md
Labels: documentation

#51 Feature/terminal flags
  README.md
  doc/designpatterns.md
  src/main/java/team/rocket/AbstractAnimal.java
  src/main/java/team/rocket/AbstractOrganism.java
  src/main/java/team/rocket/Enums/Direction.java
  src/main/java/team/rocket/Handlers/Terminal/FlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/GridSizeFlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/InitialOrganismCountFlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/TerminalFlagRequest.java
  src/main/java/team/rocket/OrganismFactory.java
  src/main/java/team/rocket/Rabbit.java
  src/main/java/team/rocket/Simulation.java
  src/test/java/stepdefinitions/OrganismFactory.java
  src/test/java/stepdefinitions/TerminalFlags/GridSizeFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/InitialOrganismCountFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/MultipleTerminalFlags.java
  src/test/java/stepdefinitions/TerminalFlags/TerminalFlagRequest.java
  src/test/resources/features/OrganismFactory.feature
  src/test/resources/features/TerminalFlags/GridSizeFlagHandler.feature
  src/test/resources/features/TerminalFlags/InitialOrganismCountFlagHandler.feature
  src/test/resources/features/TerminalFlags/MultipleTerminalFlagTests.feature
  src/test/resources/features/TerminalFlags/Request.feature
Labels: enhancement

#52 Update README.md
  README.md
Labels: documentation

#55 UI again
  src/main/java/team/rocket/Simulation.java
  src/main/java/team/rocket/UI.java
Labels: enhancement

#54 Animal movement
  src/main/java/team/rocket/AbstractAnimal.java
  src/main/java/team/rocket/Rabbit.java
Labels: enhancement

#59 Doc/sprint2 md
  doc/s2pics/MapS2.png
  doc/s2pics/OneCommandTestsS2.png
  doc/s2pics/TerminalFlagHandlerS2.png
  doc/s2pics/TerminalFlagReadmeS2.png
  doc/sprint2.md
Labels: documentation

#61 Fix/terminal flag handler
  README.md
  doc/UMLdiagrams/OrganismFactory.plantuml
  doc/UMLdiagrams/OrganismFactory.png
  doc/UMLdiagrams/OrganismFactory.uml
  doc/UMLdiagrams/TerminalFlagHandler.plantuml
  doc/UMLdiagrams/TerminalFlagHandler.png
  doc/UMLdiagrams/TerminalFlagHandler.uml
  src/main/java/team/rocket/Entities/AbstractAnimal.java
  src/main/java/team/rocket/Entities/AbstractOrganism.java
  src/main/java/team/rocket/Entities/AbstractPlant.java
  src/main/java/team/rocket/Entities/Grass.java
  src/main/java/team/rocket/Entities/OrganismFactory.java
  src/main/java/team/rocket/Entities/Rabbit.java
  src/main/java/team/rocket/Handlers/Terminal/InitialOrganismCountFlagHandler.java
  src/main/java/team/rocket/Map.java
  src/main/java/team/rocket/Simulation.java
  src/main/java/team/rocket/UI.java
  src/test/java/stepdefinitions/Grass.java
  src/test/java/stepdefinitions/Map.java
  src/test/java/stepdefinitions/OrganismFactory.java
  src/test/java/stepdefinitions/TerminalFlags/GridSizeFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/InitialOrganismCountFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/MultipleTerminalFlags.java
Labels: bug

#68 Added foxes and testing
  src/main/java/team/rocket/Entities/AbstractOrganism.java
  src/main/java/team/rocket/Entities/Fox.java
  src/main/java/team/rocket/UI.java
  src/test/java/stepdefinitions/Fox.java
  src/test/resources/features/Fox.feature
Labels: enhancement

#74 Doc/sprint 3 file
  doc/DesignDiagrams/Class_Architecture.drawio.png
  doc/DesignDiagrams/Team_Rocket_Development_Process.png
  doc/sprint3.md
Labels: documentation

#86 Update architecture.md
  doc/architecture.md
Labels: bug, documentation

#85 Added version values to all components, and did some small readme updates
  README.md
  build.gradle.kts
  src/main/java/team/rocket/Entities/AbstractAnimal.java
  src/main/java/team/rocket/Entities/AbstractOrganism.java
  src/main/java/team/rocket/Entities/AbstractPlant.java
  src/main/java/team/rocket/Entities/Fox.java
  src/main/java/team/rocket/Entities/Grass.java
  src/main/java/team/rocket/Entities/OrganismFactory.java
  src/main/java/team/rocket/Entities/Rabbit.java
  src/main/java/team/rocket/Enums/Direction.java
  src/main/java/team/rocket/Handlers/Terminal/FlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/GridSizeFlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/InitialOrganismCountFlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/TerminalFlagRequest.java
  src/main/java/team/rocket/Map.java
  src/main/java/team/rocket/Simulation.java
  src/main/java/team/rocket/UI.java
Labels: documentation

#88 Feature/GitHub actions
  .github/workflows/gradle.yml
Labels: enhancement, testing

#92 tests for UI have been added
  src/main/java/team/rocket/UI.java
  src/test/java/stepdefinitions/Map.java
  src/test/java/stepdefinitions/Simulation.java
  src/test/java/stepdefinitions/UI.java
  src/test/resources/features/Simulation.feature
  src/test/resources/features/UI.feature
Labels: testing

#91 Feature/time step flag
  README.md
  doc/UMLdiagrams/TerminalFlagHandler.plantuml
  doc/UMLdiagrams/TerminalFlagHandler.png
  doc/UMLdiagrams/TerminalFlagHandler.uml
  doc/architecture.md
  src/main/java/team/rocket/Handlers/Terminal/DaysPerRunFlagHandler.java
  src/main/java/team/rocket/Handlers/Terminal/TerminalFlagRequest.java
  src/main/java/team/rocket/Handlers/Terminal/TimeStepsPerDayFlagHandler.java
  src/main/java/team/rocket/UI.java
  src/test/java/stepdefinitions/TerminalFlags/DaysPerRunFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/TerminalFlagRequest.java
  src/test/java/stepdefinitions/TerminalFlags/TimeStepsPerDayFlagHandler.java
  src/test/resources/features/TerminalFlags/DaysPerRunFlagHandler.feature
  src/test/resources/features/TerminalFlags/Request.feature
  src/test/resources/features/TerminalFlags/TimeStepsPerDayFlagHandler.feature
Labels: enhancement

#89 Doc/testing documentation
  doc/testing.md
Labels: documentation

#93 Debug/adding simulation tests
  src/main/java/team/rocket/Handlers/Terminal/TerminalFlagRequest.java
  src/main/java/team/rocket/Simulation.java
  src/test/java/stepdefinitions/Simulation.java
  src/test/java/stepdefinitions/TerminalFlags/TerminalFlagRequest.java
  src/test/resources/features/Simulation.feature
Labels: bug, testing
