Repository IUS-CS/c346-fa23-project-team-rocket, pull requests merged in 2023-11, with the labels that each got.

#96 Readme fix
  README.md
  doc/architecture.md
Labels: documentation

#94 Breeding has been modified
  src/main/java/team/rocket/Simulation.java
  src/test/java/stepdefinitions/Simulation.java
Labels: enhancement

#101 Doc/sprint4 md
  doc/s4pics/Githubactions_S4.png
  doc/s4pics/pathfinding_flow.png
  doc/s4pics/updatedReadme_S4.png
  doc/sprint4.md
Labels: documentation

#102 Doc/version change
  README.md
  build.gradle.kts
Labels: documentation

#112 Organism vision
  src/main/java/team/rocket/Entities/AbstractAnimal.java
  src/main/java/team/rocket/Entities/Fox.java
  src/main/java/team/rocket/Entities/Rabbit.java
  src/test/java/stepdefinitions/Fox.java
  src/test/java/stepdefinitions/Rabbit.java
  src/test/java/stepdefinitions/Vision.java
  src/test/resources/features/Fox.feature
  src/test/resources/features/Rabbit.feature
  src/test/resources/features/Vision.feature
Labels: enhancement

#113 Feature/io optimization work
  build.gradle.kts
  src/main/java/team/rocket/Entities/Rabbit.java
  src/main/java/team/rocket/IO/Terminal/DaysPerRunFlagHandler.java
  src/main/java/team/rocket/IO/Terminal/FlagHandler.java
  src/main/java/team/rocket/IO/Terminal/GridSizeFlagHandler.java
  src/main/java/team/rocket/IO/Terminal/InitialOrganismCountFlagHandler.java
  src/main/java/team/rocket/IO/Terminal/TerminalFlagRequest.java
  src/main/java/team/rocket/IO/Terminal/TimeStepsPerDayFlagHandler.java
  src/main/java/team/rocket/IO/UI.java
  src/main/java/team/rocket/Simulation.java
  src/test/java/stepdefinitions/TerminalFlags/DaysPerRunFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/GridSizeFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/InitialOrganismCountFlagHandler.java
  src/test/java/stepdefinitions/TerminalFlags/MultipleTerminalFlags.java
  src/test/java/stepdefinitions/TerminalFlags/TerminalFlagRequest.java
  src/test/java/stepdefinitions/TerminalFlags/TimeStepsPerDayFlagHandler.java
  src/test/java/stepdefinitions/UI.java
Labels: enhancement

#114 Feature/simulation optimization work
  src/main/java/team/rocket/Entities/Carrot.java
  src/main/java/team/rocket/Entities/Fox.java
  src/main/java/team/rocket/Entities/Grass.java
  src/main/java/team/rocket/Entities/Rabbit.java
  src/main/java/team/rocket/Enums/Direction.java
  src/main/java/team/rocket/IO/UI.java
  src/main/java/team/rocket/Map.java
  src/main/java/team/rocket/Simulation.java
  src/main/java/team/rocket/util/RandomManager.java
  src/main/java/team/rocket/util/TimeManager.java
  src/test/java/stepdefinitions/Direction.java
  src/test/java/stepdefinitions/Map.java
  src/test/java/stepdefinitions/Simulation.java
  src/test/resources/features/Direction.feature
  src/test/resources/features/Map.feature
Labels: enhancement

#99 Integration testing
  doc/IntegrationTesting.md
Labels: documentation

#117 Animal eating
  src/main/java/team/rocket/Entities/AbstractAnimal.java
  src/main/java/team/rocket/Entities/AbstractOrganism.java
  src/main/java/team/rocket/Entities/AbstractPlant.java
  src/main/java/team/rocket/Entities/Carrot.java
  src/main/java/team/rocket/Entities/Fox.java
  src/main/java/team/rocket/Entities/Grass.java
  src/main/java/team/rocket/Entities/Rabbit.java
  src/main/java/team/rocket/Simulation.java
  src/test/java/stepdefinitions/Fox.java
  src/test/java/stepdefinitions/Rabbit.java
  src/test/resources/features/Fox.feature
  src/test/resources/features/Rabbit.feature
Labels: enhancement

#116 breeding spawn distance fix
  src/main/java/team/rocket/Simulation.java
Labels: bug, enhancement

#119 Problem with day 0 printing before day 1 is fixed now.
  src/main/java/team/rocket/IO/UI.java
  src/main/java/team/rocket/Simulation.java
Labels: bug

#128 Doc/tutorial
  README.md
  doc/tutorial.md
Labels: documentation

#127 Doc/projectreflections
  doc/projectreflections.md
Labels: documentation

#121 Feature/version change
  README.md
  build.gradle.kts
Labels: documentation

#120 Doc/sprint5 retro
  doc/s5pics/EnumImprovements_S5.png
  doc/s5pics/Nutrition_S5.png
  doc/s5pics/deleteme.txt
  doc/s5pics/numberOfOrganisms_S5.png
  doc/s5pics/profiler_S5.png
  doc/sprint5.md
Labels: documentation
