Repository IUS-CS/c346-fa23-project-team-rocket, pull requests merged in 2023-09, with the labels that each got.

#1 Created the AUTHORS file and added author names
  AUTHORS
Labels: enhancement

#2 Feature/gitignore
  .gitignore
Labels: enhancement

#21 Used the gradle install daemon, and double checked that the file stru…
  .gitattributes
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: enhancement

#26 Organization
  doc/organization.md
  gradlew.bat
Labels: documentation

#25 Proposal
  doc/proposal.md
Labels: documentation

#27 Feature/cucumber testing
  build.gradle.kts
  src/test/java/stepdefinitions/test_1.java
  src/test/resources/features/test_1.feature
Labels: testing

#37 Documentation/sprint 1
  doc/s1pics/GitignorePictureS1.png
  doc/s1pics/GradleBuildPictureS1.png
  doc/s1pics/ProposalPictureS1.png
  doc/s1pics/ReadmePictureS1.png
  doc/s1pics/RunningSimulationProgramS1.png
  doc/sprint1.md
Labels: documentation

#39 Test/improving build test and merge functions
  build.gradle.kts
  src/main/java/team/rocket/AbstractAnimal.java
  src/main/java/team/rocket/Direction.java
  src/main/java/team/rocket/Rabbit.java
  src/main/java/team/rocket/Simulation.java
  src/test/java/stepdefinitions/test_1.java
Labels: testing

#40 Abstract Organism
  src/main/java/team/rocket/AbstractAnimal.java
  src/main/java/team/rocket/AbstractOrganism.java
  src/main/java/team/rocket/Rabbit.java
Labels: enhancement

#46 Map
  build.gradle.kts
  doc/sprint1.md
  src/main/java/team/rocket/Map.java
  src/test/java/stepdefinitions/Map.java
  src/test/java/stepdefinitions/test_1.java
  src/test/resources/features/Map.feature
  src/test/resources/features/test_1.feature
Labels: enhancement
